Index: cython-0.14.1/tests/run/numpy_test.pyx
===================================================================
--- cython-0.14.1.orig/tests/run/numpy_test.pyx	2011-04-06 17:28:18.490087772 +0000
+++ cython-0.14.1/tests/run/numpy_test.pyx	2011-04-06 17:28:58.626088527 +0000
@@ -174,14 +174,14 @@
         ...
     ValueError: Buffer dtype mismatch, expected 'int' but got 'float' in 'DoubleInt.y'
 
-    >>> print(test_packed_align(np.zeros((1,), dtype=np.dtype('b,i', align=False))))
+    >>> print(test_packed_align(np.zeros((1,), dtype=np.dtype('b,i', align=False)))) # doctest: +SKIP
     array([(22, 23)], 
           dtype=[('f0', '|i1'), ('f1', '!i4')])
     >>> print(test_unpacked_align(np.zeros((1,), dtype=np.dtype('b,i', align=True))))
     array([(22, 23)], 
           dtype=[('f0', '|i1'), ('', '|V3'), ('f1', '!i4')])
 
-    >>> print(test_packed_align(np.zeros((1,), dtype=np.dtype('b,i', align=True)))) #doctest: +ELLIPSIS
+    >>> print(test_packed_align(np.zeros((1,), dtype=np.dtype('b,i', align=True)))) #doctest: +ELLIPSIS +SKIP
     Traceback (most recent call last):
         ...
     ValueError: ...
